[package]
name = "anyrun"
version = "25.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyrun-macros = { path = "../anyrun-macros" }
abi_stable = "0.11.1"
ron = "0.8.0"
serde = { version = "1.0.210", features = ["derive"] }
anyrun-interface = { path = "../anyrun-interface" }
wl-clipboard-rs = "0.9.1"
nix = { version = "0.29", default-features = false, features = ["process"] }
clap = { version = "4.2.7", features = ["derive"] }
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
relm4 = "0.9.1"
gtk4-layer-shell = "0.5.0"
gtk4 = "0.9.0"
