name: "Set up binary cache & push binaries"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  cachix:
    name: "Build Exposed Packages"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - anyrun
          - applications
          - dictionary
          - kidex
          - randr
          - rink
          - shell
          - stdin
          - symbols
          - websearch
    steps:
      - uses: easimon/maximize-build-space@v8
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-docker-images: true
          remove-codeql: true

      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          name: anyrun

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch main

      - name: Build anyrun from the defined matrix
        run: nix build .#${{ matrix.package }} --print-build-logs --extra-substituters "https://anyrun.cachix.org"
