name: "Check flake & Push built packages to cache"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  check-flake:
    name: "Check flake validity"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Flake
        run: nix flake check --accept-flake-config

  cachix:
    name: "Build & Cache Exposed Packages"
    runs-on: ubuntu-latest
    needs: check-flake
    strategy:
      matrix:
        package:
          - anyrun
          - applications
          - dictionary
          - kidex
          - randr
          - rink
          - shell
          - stdin
          - symbols
          - websearch
    steps:
      - uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-docker-images: true
          remove-codeql: true

      - name: Checkout
        uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          name: anyrun

      - name: Build anyrun from the defined matrix
        run: nix build .#${{ matrix.package }} --print-build-logs --extra-substituters "https://anyrun.cachix.org"
